project:
  type: website
lang: es
website:
  page-navigation: true
  back-to-top-navigation: false
  search:
    type: textbox
    copy-button: true
  repo-url: https://github.com/IIQ2043/workbook
  repo-actions: source

  page-footer: 
    background: secondary
    left: "2024, Ignacio Tabilo"
    right:
      - icon: github
        href: https://github.com/IIQ2043/workbook
      - icon: code-square
        href: https://quarto.org/

  sidebar:
    alignment: center
    footer: "Material complementario"
    logo: logo.png
    title: "IIQ2043"
    background: light
    collapse-level: 1
    style: docked
    contents:
      - index.qmd
      - text: "Fundamentos"
      - text: "---"
      - mc_glos.qmd
      - mc_eos.qmd
      - mc_fug.qmd
      - mc_mix.qmd

format:
  html:
    page-layout: full
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-expand: true
    toc-title: "Contenido"
    grid: 
      body-width: 800px
      sidebar-width: 250px
      margin-width: 300px
      gutter-width: 2em
    tbl-cap-location: bottom

