project:
  type: website

website:
  title: "workbook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - prueba.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



