---
title: "Modelos termodinámicos"
format: html
filters:
  - shinylive
---

[comment]: <> (ToDo: Cambiar las lecturas requeridas. Añadir tabla en la sección de teŕminos. Añadir colores al texto. Añadir label a la celda shiny.)

::: {.callout-warning appearance="simple"}
## Importante

En esta sección se espera que el alumno maneje conceptos tales como: Diagramas *P-V-T*; propiedades críticas; gas ideal; conocimientos básicos sobre la entalpía y entropía. En caso de querer reforzar algún concepto mencionado, se recomienda leer la sección 2.2 del libro <a href="https://bmdigitales-bibliotecas-uc-cl.pucdechile.idm.oclc.org/html5/FUNDAMENTALS%20OF%20CHEMICAL%20ENGINEERING%20THERMODYNAMICS%20K.%20D.%20DAHM/">Fundamentals of Chemical Engineering Thermodynamics</a> (páginas 49-57).

:::

## Motivación: Primera ley de la termodinámica

Los fluidos, al estar compuestos de moléculas, tienen una energía intrínseca que les pertenece: la energía interna. En los sistema que estudiamos suele ser importante entender cómo la energía interna se transforma en otras formas de energía (calor, trabajo, energía cinética, entre otras). Ya que la relación entre ellas depende del sistema que estemos evaluando, utilizamos balances de energía para comprender lo que ocurre en un equipo o una planta química completa.

::::: {.columns}

:::: {.column width="68%" align=center}
La ecuación generalizada,
$$
d\left(U + \frac{Mv^2}{2} + Mgh\right) = \delta W + \delta Q + \sum_{in} \delta m_{in}\left( \hat{H}_{in} + \frac{v^2_{in}}{2} + gh_{in} \right)
$$
$$
- \sum_{out} \delta m_{out}\left( \hat{H}_{out} + \frac{v^2_{out}}{2} + gh_{out} \right)
$$

puede parecer compleja o tediosa de calcular. En este caso se considera un **sistema abierto**, el cuál se somete a cambios de energía producidos en presencia de trabajo de eje; calor; energía interna, potencial y cinética; entrada y salida de energía, expansión y compresión. En la práctica, los sistemas presentan solo algunos de los factores considerados en la ecuación generalizada.

::::

:::: {.column width="2%"}
::::

:::: {.column width="30%"}

::: {.callout-note}
## Parámetros y variables

* $U$: Energía interna ($\text{J}$)
* $M$: Masa total en el sistema ($\text{kg}$)
* $v$: Velocidad ($\text{m}\cdot\text{s}^{-1}$)
* $h$: Altura ($\text{m}$)
* $\hat{H}$: Entalpía específica ($\text{J}\cdot\text{kg}^{-1}$)
* $\delta m_{in}$ o $\delta m_{out}$: Masa que entra o sale del sistema ($\text{kg}$)
* $W$: Trabajo que entra al sistema. Puede ser de eje, expansión y/o compresión ($\text{J}$)
* $Q$: Calor que entra al sistema ($\text{J}$)

:::

::::

:::::

Otra forma de encontrar esta ecuación es en su forma **transiente**, en otras palabras, considerando la variación en el tiempo.

$$
\frac{d}{dt}\left[M\left(\hat{U} + \frac{v^2}{2} + gh\right)\right] = \dot{W} + \dot{Q} + \sum_{in} \dot{m}_{in}\left( \hat{H}_{in} + \frac{v^2_{in}}{2} + gh_{in} \right) - \sum_{out} \dot{m}_{out}\left( \hat{H}_{out} + \frac{v^2_{out}}{2} + gh_{out} \right)
$$

Sin embargo, en la mayoría de libros y cursos de termodinámica se presenta el balance de energía para sistemas **no transientes y cerrados** bajo el nombre de la primera ley de la termodinámica.

$$
\delta U = \delta W + \delta Q
$$

 Independientemente de nuestro sistema, ya sea una bomba, una turbina, una válvula o una caldera, el balance de energía tiene un rol fundamental en definir el comportamiento de este.
 
 El siguiente paso para evaluar nuestro sistema sería cuantificar los cambios energéticos. Esto se consigue **midiendo** las variaciones de energía. Aquí que surge un problema: no es posible medir la energía interna $U$. Esto último no se puede hacer de forma directa, y en consecuencia, existe una necesidad de definir las propiedades termodinámicas en función de **unidades medibles**: presión ($P$), volumen ($V$) y temperatura ($T$).

::: {.callout-important collapse="true"}
## Sobre la notación

En esta página se utilizará la siguiente notación.

Volúmen: $V~\text{(m}^3\text{)}$

Volúmen másico: $\hat{V}~\text{(m}^3\cdot\text{kg}^{-1}\text{)}$

Volúmen molar: $\underline{V}~\text{(m}^3\cdot\text{mol}^{-1}\text{)}$

:::


<br>

## Propiedades de los compuestos puros

Antes de continuar, es importante hacer un paréntesis con respecto a las **propiedades de estado**. Estas son aquellas características de la condición en la que se encuentra un compuesto o sistema. Sin importar el cómo se llego a esa condición, las propiedades de estado siempre serán las mismas. Eso significa que la energía interna del agua a $25~^\circ\text{C}$ y $1$ atmósfera será siempre la misma idependientemente de la manera en que se llegó a la condición, siempre y cuando los sistemas sean iguales.

Existen propiedades de estado que son de suma importancia para el estudio de la termodinámica. Las ecuaciones que las describen se denominan **ecuaciones fundamentales de la termodinámica** y entre ellas se encuentra la energía interna.

| Propiedad              | Ecuación        | Variables naturales |
|------------------------|-----------------|---------------------|
| Energía interna        | $dU = TdS-PdV$  | $U(S,~V)$           |
| Energía de Helmholtz   | $dA = SdT-PdV$  | $A(T,~V)$           |
| Entalpía               | $dH = TdS+VdP$  | $H(S,~P)$           |
| Energía libre de Gibbs | $dG = -SdT+VdP$ | $G(T,~P)$           |

: Tabla: Ecuaciones fundamentales {.hover}

A partir de estas ecuaciones, las relaciones de Maxwell y las herramientas de cálculo que se aprenden en el curso, es posible describir los cambios en las propiedades de un estado a otro (para compuestos puros). De esta manera, podemos cumplir con nuestro objetivo de **relacionar la energía con propiedades medibles**. Pongamos a prueba esto a través de un ejercicio.

::: {.callout-tip appearance="simple"}

## Ejercicio

Es común suponer que la entalpía de un fluido que entra a una válvula es la misma que posee al salir de esta (isoentalpía); se desea relacionar la entalpía con unidades medibles. Demuestre a partir de la expresión:

$$
dH = \left(\frac{\partial H}{\partial T}\right)_PdT + \left(\frac{\partial H}{\partial P}\right)_TdP
$$

Que se puede llegar a la siguiente ecuación que relaciona la entalpía con la presión, temperatura y volumen.

$$
dH = c_PdT + \left[ V - T\left(\frac{\partial V}{\partial T}\right)_P\right]dP
$$

:::

Fijémonos en la solución del ejercicio anterior. A pesar de que la entalpía quedó expresada únicamente en función de $P$, $V$ y $T$, ¿cómo podríamos calcular $\left(\partial V/\partial T\right)_P$? Aún necesitamos encontrar alguna función que relacione estas propiedades entre sí. Para esto tenemos las **ecuaciones de estado**.

<br>

## Ecuaciones de estado (EoS)

Las ecuaciones de estado relacionan las propiedades de presión ($P$), volúmen ($V$) y temperatura ($T$) en base a fundamentos teóricos del comportamiento molecular de los compuestos. En otras palabras, **las *EoS* explican el comportamiento macroscópico de los fluidos a partir de lo microscópico**. Entender en profundidad cada ecuación de estado no es la finalidad de este curso. Lo más importante es que entiendan los motivos por los cuales se utilizan y, también, que formen una idea general de los términos que aparecen en ellas.

### Ecuaciones de estado típicas


| | Ecuación de estado | Fórmula | |
|---|:-:|:-:|---|
| | Gas ideal | $$ P\underline{V} = RT $$ | |
| | Van der Waals | $$ P = \frac{RT}{\underline{V}-b}-\frac{a}{\underline{V}^2} $$ | |
| | Redlich-Kwong | $$ P = \frac{RT}{\underline{V}-b} - \frac{a}{\sqrt{T}\underline{V}\left(\underline{V}+b\right)} $$ | |
| | Peng-Robinson | $$ P = \frac{RT}{\underline{V}-b} - \frac{\alpha a(T)}{\underline{V}^2+2b\underline{V}-b^2} $$ | |

: Ecuaciones de Estado básicas y Cúbicas {tbl-colwidths="[10,20,60,10]" .hover}

### Términos asociados a los principios de Lennard-Jones

::::: {.columns}

:::: {.column width="64%" align=center}

\
El potencial de Lennard-Jones es un modelo de interacción molecular que describe el comportamiento de atracción y repulsión entre dos moléculas.
$$
\Gamma = 4\varepsilon\left[\left(\frac{\sigma}{r}\right)^{12}-\left(\frac{\sigma}{r}\right)^{6}\right]
$$

A nosotros solo nos interesa saber que algunos modelos termodinámicos se basan en los principios propuestos por este modelo para mejorar su capacidad de predicción.

::::

:::: {.column width="2%"}
::::

:::: {.column width="34%"}

::: {.callout-note}
## Parámetros y variables

* $\Gamma$: Energía potencial intermolecular.
* $r$: Distancia entre las dos moléculas.
* $\sigma$: Distancia a la cual las moléculas pasan de atraerse ($\Gamma<0$) a repelerse ($\Gamma>0$).
* $\varepsilon$: Energía potencial máxima de atracción.

:::

::::

:::::

| Parámetro   |Significado   |
|:-----------:|:-------------|
| **Término atractivo $(a)$** | En las *EoS* tipo Van der Waals se incluye este término para representar la **atracción entre las moléculas**. Lennard-Jones propone que esta interacción es dependiente de la polaridad de las moléculas y de la distancia entre ellas (Basado en la Ley de Coulomb). |
| **Término de exclusión por volumen $(b)$** | Este parámetro representa el volumen que **no** puede ocupar un molécula a causa de que otra se encuentre en dicho espacio. En términos de Lennard-Jones: a medida que una molécula se acerca a otra, la energía potencial repulsiva entre ellas tiende a infinito por lo que nunca se tocan. Por eso, este parámetro se conoce como el **término repulsivo**. |
| **factor acéntrico $(\omega)$** | Este parámetro representa la **no esfericidad de las moléculas**. El supuesto de esfericidad es relativamente cierto para moléculas pequeñas, pero limita la aplicabilidad del modelo. |
| **Efecto de la temperatura en la interacción molecular $(a\left[T\right])$** | La temperatura impacta directamente la forma en que las moléculas interactuan y se atraen. Ecuaciones como Peng-Robinson representan esta dependencia para mejorar su capacidad predictiva en distintas condiciones de operación. |

: Parámetros típicos en las ecuaciones de estado {tbl-colwidths="[20,80]" .hover}

<br>

## Ejemplo: Diagrama PV para CO$_2$

Pongamos a prueba la teoría con una modelación. Suponga que desea predecir la relación PVT para dióxido de carbono. Para esto usted usará dos ecuaciones de estado: **Van der Waals** y **Peng-Robinson**. La validación experimental se hará en base a la **curva de saturación** real de CO$_2$ (NIST). Las ecuaciones de estos modelos son las siguientes:

$$
\text{Van der Waals:}~~~P = \frac{RT}{\underline{V}-b}-\frac{a}{\underline{V}^2}
$$ {#eq-vdw}

$$
\text{donde,}~~a = \frac{27}{64}\frac{(RT_c)^2}{P_c}~;~~ b = \frac{1}{8}\frac{RT_c}{P_c}
$$

$$
\text{Peng-Robinson:}~~~P = \frac{RT}{\underline{V}-b}-\frac{a\alpha(T)}{\underline{V}^2+2b\underline{V}-b^2}
$$ {#eq-pr}

$$
\text{donde,}~~a = 0.45724\frac{(RT_c)^2}{P_c}~;~~ b = 0.0778\frac{RT_c}{P_c}
$$
$$
\alpha(T)=\left(1+\left(0.37464 + 1.54226\omega + 0.26992\omega^2\right)\times\left(1-T_r^{0.5}\right)\right)^2
$$
Notar que Peng-Robinson considera tanto los parámetros $a$ y $b$, como los parámetros $\omega$ y la dependencia de temperatura para el término de interacción. A continuación un gráfico comparativo entre ambas *EoS*.
```{shinylive-python}
#| standalone: true
#| viewerHeight: 550

from shiny import *
import numpy as np
from scipy.optimize import fsolve
import matplotlib.pyplot as plt

AnimationOptions = {'interval': 200,'loop': False}

app_ui = ui.page_sidebar(
  ui.sidebar(
    "Ecuaciones de estado:",
    ui.input_switch("switch_vdw","Van der Waals", value=True),
    ui.input_switch("switch_pr","Peng-Robinson", value=True),
    ui.input_slider("T","Isolínea de Temperatura:", min=285,max=315,value=289,step=3,animate=AnimationOptions,post=" K"),
    width=300),
  ui.output_plot("plot")
)


def server(input, output, session):
  
  # Propiedades termodinámicas CO2 TODAS DE NIST DATABASE (Suehiro, Nakajima, et al., 1996)
  Tc = 304.18 #K
  Pc = 73.80e5 #Pa
  omega = 0.239
  V = np.linspace(50e-6, 380e-6, 330) #m3/mol
  R = 8.314

  ######################## SAT (NIST) ########################
  Psat_exp = [4, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7, 7.1, 7.2, 7.3, 7.314, 7.328, 7.342, 7.356, 7.37, 7.38, 7.37, 7.356, 7.342, 7.328, 7.314, 7.3, 7.2, 7.1, 7, 6.9, 6.8, 6.7, 6.6, 6.5, 6.4, 6.3, 6.2, 6.1, 6, 5.9, 5.8, 5.7, 5.6, 5.5, 5.4, 5.3, 5.2, 5.1, 5, 4.9, 4.8, 4.7, 4.6, 4.5, 4.4, 4.3, 4.2, 4.1, 4]
  vsat_exp = [49.225, 49.586, 49.953, 50.327, 50.709, 51.099, 51.498, 51.906, 52.324, 52.754, 53.196, 53.651, 54.12, 54.605, 55.108, 55.629, 56.171, 56.736, 57.327, 57.947, 58.599, 59.288, 60.019, 60.8, 61.639, 62.548, 63.541, 64.64, 65.873, 67.285, 68.948, 70.993, 73.717, 78.051, 78.96, 80.025, 81.328, 83.06, 85.936, 91.9, 103.51, 108.16, 111.28, 113.81, 115.99, 117.95, 128.82, 137.29, 144.75, 151.68, 158.28, 164.69, 170.98, 177.22, 183.44, 189.67, 195.94, 202.28, 208.69, 215.21, 221.84, 228.6, 235.5, 242.57, 249.82, 257.26, 264.91, 272.78, 280.9, 289.28, 297.94, 306.91, 316.2, 325.84, 335.85, 346.26, 357.11, 368.43, 380.24]
  ################# v (cm3/mol) // p (MPa) ###################

  ## VAN DER WAALS
  @reactive.calc
  def vdw_eos():
    T = input.T()
    a = 27/64 * (R*Tc)**2/Pc
    b = 1/8 * (R*Tc)/Pc
    P = []
    for v in V:
      p = (R*T)/(v-b) - a/v**2
      P.append(p/10**6)
    
    return V*10**6, P
  
  @reactive.calc
  def vdw_isofug():
    T = input.T()
    a = 27/64 * (R*Tc)**2/Pc
    b = 1/8 * (R*Tc)/Pc
    v0 =[80e-6, 230e-6, 5.3e6] # Esto funciona, simplemente con prueba y error entre los límites (280K - <Tc)

    def solver_vdw(I):
      vL, vV, Psat = I
      zL = (Psat*vL)/(R*T)
      zV = (Psat*vV)/(R*T)
      phiL = np.exp(zL - 1 - a/(R*T*vL) - np.log(zL*(1 - b/vL)))
      phiV = np.exp(zV - 1 - a/(R*T*vV) - np.log(zV*(1 - b/vV)))
      pL = (R*T)/(vL-b) - a/vL**2
      pV = (R*T)/(vV-b) - a/vV**2

      f1 = phiL - phiV
      f2 = pL - Psat
      f3 = pV - Psat
      return [f1,f2,f3]
    
    vdw_sol = fsolve(solver_vdw, v0)
    return vdw_sol
  
  ## PENG-ROBINSON
  @reactive.calc
  def pr_eos():
    T = input.T()
    a = 0.45724 * (R*Tc)**2/Pc
    alpha = (1 + (0.37464 + 1.54226*omega - 0.26992*omega**2)*(1-(T/Tc)**(1/2)))**2
    b = 0.0778 * (R*Tc)/Pc
    P = []
    for v in V:
      p = (R*T)/(v-b) - (a*alpha)/(v**2+2*b*v-b**2)
      P.append(p/10**6)
    
    return V*10**6, P
  
  @reactive.calc
  def pr_isofug():
    T = input.T()
    a = 0.45724 * (R*Tc)**2/Pc
    alpha = (1 + (0.37464 + 1.54226*omega - 0.26992*omega**2)*(1-(T/Tc)**(1/2)))**2
    b = 0.0778 * (R*Tc)/Pc

    v0 =[60e-6, 190e-6, 5.3e6] # Esto funciona, simplemente con prueba y error entre los límites (280K - <Tc)

    def solver_pr(I):
      vL, vV, Psat = I
      A = (a*alpha*Psat)/(R*T)**2
      B = (b*Psat)/(R*T)
      zL = (Psat*vL)/(R*T)
      zV = (Psat*vV)/(R*T)

      phiL = np.exp(zL - 1 - np.log(zL - B) - A/(B*8**(1/2))*np.log((zL+(1+2**(1/2))*B)/(zL+(1-2**(1/2))*B)))
      phiV = np.exp(zV - 1 - np.log(zV - B) - A/(B*8**(1/2))*np.log((zV+(1+2**(1/2))*B)/(zV+(1-2**(1/2))*B)))
      pL = (R*T)/(vL-b) - (a*alpha)/(vL**2+2*b*vL-b**2)
      pV = (R*T)/(vV-b) - (a*alpha)/(vV**2+2*b*vV-b**2)

      f1 = phiL - phiV
      f2 = pL - Psat
      f3 = pV - Psat
      return [f1,f2,f3]
    
    pr_sol = fsolve(solver_pr, v0)
    return pr_sol

  # Graficar

  @render.plot(width=550,height=500)
  def plot():

    if input.switch_vdw():
      v_vdw, P_vdw = vdw_eos() # retorna en cm3/mol y MPa
      plt.plot(v_vdw, P_vdw, c="#7e9da2", label="Van der Waals")
      
      if input.T() < Tc:
        vL_vdw, vV_vdw, Psat_vdw = vdw_isofug() # retorna en m3/mol y Pa
        plt.plot([vL_vdw*10**6,vV_vdw*10**6], [Psat_vdw*10**(-6),Psat_vdw*10**(-6)], c="#7e9da2", linestyle='dashed')

    if input.switch_pr():
      v_pr, P_pr = pr_eos() # retorna en cm3/mol y MPa
      plt.plot(v_pr, P_pr, c="#cc3739", label="Peng-Robinson")
      
      if input.T() < Tc:
        vL_pr, vV_pr, Psat_pr = pr_isofug() # retorna en m3/mol y Pa
        plt.plot([vL_pr*10**6,vV_pr*10**6], [Psat_pr*10**(-6),Psat_pr*10**(-6)], c="#cc3739", linestyle='dashed')
      

    plt.plot(vsat_exp, Psat_exp, c="#0e150d", label="Curva de saturación")
    plt.legend()
    plt.xlabel("Volumen molar / cm$^3\cdot$mol$^{-1}$")
    plt.ylabel("Presión / MPa")
    plt.xlim([50,380])
    plt.ylim([4,10])
    plt.show()

app = App(app_ui, server)

```

[comment]: <> (No me gusta esta parte final, añadiría una label a la celda de código, util para poder citarla eventualmente, quizás podría ponerle colores al texto para identificar las curvas. Me gusta la idea de añadir colores al texto en general.)

En la figura, las líneas continuas representan las ecuaciones [-@eq-vdw] y [-@eq-pr]. Es importante notar que bajo la curva de saturación, ambas EoS presentan un comportamiento que no sigue el patrón esperado. Usualmente, aprendemos que, a presión constante, la temperatura permanece estable hasta que ocurre el cambio de fase, o que, a temperatura constante (como en el gráfico), la presión se mantiene fija hasta que el cambio de fase tiene lugar. Sin embargo, estas ecuaciones de estado no parecen cumplir con esta observación.

Para definir correctamente el cambio de fase, necesitamos recurrir a la **energía libre de Gibbs** o, de manera equivalente, a la **fugacidad**. La fugacidad en el gráfico está representada por la línea discontinua y su predicción depende de la ecuación de estado utilizada. El objetivo de esta sección no es explicar la fugacidad. De momento, es preferible analizar el gráfico y responder las siguientes preguntas.

::: {.callout-tip}
## Preguntas

¿Qué modelo predice mejor la curva de saturación? ¿Existen diferencias entre las presiones de saturación entre los modelos? ¿Qué puede decir sobre las predicciones en fase gaseosa? ¿Y en fase líquida?

:::
